services:
  backend:
    depends_on:
      - db
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - internal
    volumes:
      - shared_tmp:/tmp

  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - internal

networks:
  internal:

volumes:
  postgres_data:
  mongo_data:
  shared_tmp:
